notifications:
  email: false

language: node_js

node_js:
  - '4.2.4'

branches:
  only:
    - master

before_script: "npm run-script runserver 2>&1 >/dev/null &"

script: "sleep 10 && ./test/run.js"
