env:
  projectname: "myProject"
  baseUrl: "http://webdriverjs.christian-bromann.com"

selenium:
  host: "0.0.0.0"
  port: 4444

options:
  logLevel: "silent"

  # user: "cb-onboarding"
  # key: "XXXXXX-XX"

  desiredCapabilities:
    browserName: "phantomjs"
